unit Syslei.Models.Entities.Lote.Venda;

interface

uses
  Syslei.Models.Entities.Lote,
  Syslei.Models.Entities.Pessoa,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('VENDA_LOTE')]
  {$IFDEF FIREBIRD_DB}
  [Sequence('GEN_VENDA_LOTE_ID', 0, 1)]
  {$ENDIF}
  TVendaLote = class
  private
    [Column('ID', [cpPrimaryKey])]
    {$IFDEF SQLITE_DB}
    [AutoGenerated]
    {$ENDIF}
    FId: Integer;
    [Column('DATA')]
    FData: TDate;

    [Column('COMPRADOR_ID')]
    [ForeignJoinColumn('CompradorId', 'PESSOA', 'ID', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    FCompradorId: Integer;
    [ManyToOne(True, [ckCascadeAll], 'FCompradorId')]
    FComprador: TPessoa;

    [Column('LOTE_ID')]
    [ForeignJoinColumn('LoteId', 'LOTE', 'ID', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    FLoteId: Integer;
    [ManyToOne(True, [ckCascadeAll], 'FLoteId')]
    FLote: TLote;

    [Column('LANCE_ARREMATE')]
    FLanceArremate: Double;
  public
    constructor Create; virtual;
    destructor Destroy; override;

    property Id: Integer read FId write FId;
    property Data: TDate read FData write FData;

    property CompradorId: Integer read FCompradorId write FCompradorId;
    property Comprador: TPessoa read FComprador write FComprador;

    property LoteId: Integer read FLoteId write FLoteId;
    property Lote: TLote read FLote write FLote;

    property LanceArremate: Double read FLanceArremate write FLanceArremate;
  end;

implementation

uses
  System.SysUtils;

{$REGION 'TVendaLote' }

constructor TVendaLote.Create;
begin
  inherited Create;
  FComprador := TPessoa.Create;
  FLote := TLote.Create;
  FData := Date();
end;

destructor TVendaLote.Destroy;
begin
  FreeAndNil(FComprador);
  FreeAndNil(FLote);
  inherited;
end;

{$ENDREGION}

end.
