{******************************************************************************}
{                                                                              }
{  Copyright (c) 2017, Henrique Gouveia                                        }
{                                                                              }
{  Redistribution and use in source and binary forms, with or without          }
{  modification, are permitted provided that the following conditions are met: }
{                                                                              }
{    1. Redistributions of source code must retain the above copyright notice, }
{    this list of conditions and the following disclaimer.                     }
{                                                                              }
{    2. Redistributions in binary form must reproduce the above copyright      }
{    notice, this list of conditions and the following disclaimer in the       }
{    documentation and/or other materials provided with the distribution.      }
{                                                                              }
{    3. Neither the name of the copyright holder nor the names of its          }
{    contributors may be used to endorse or promote products derived from      }
{    this software without specific prior written permission.                  }
{                                                                              }
{  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" }
{  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE   }
{  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  }
{  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE   }
{  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR         }
{  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF        }
{  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS    }
{  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN     }
{  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)     }
{  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE  }
{  POSSIBILITY OF SUCH DAMAGE.                                                 }
{                                                                              }
{******************************************************************************}

unit Syslei.Models.Entities.Lote.Venda;

interface

uses
  Syslei.Models.Entities.Lote,
  Syslei.Models.Entities.Pessoa,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('VENDA_LOTE')]
  {$IFDEF FIREBIRD_DB}
  [Sequence('GEN_VENDA_LOTE_ID', 1, 1)]
  {$ENDIF}
  TVendaLote = class
  private
    [Column('ID', [cpPrimaryKey])]
    {$IFDEF SQLITE_DB}
    [AutoGenerated]
    {$ENDIF}
    FId: Integer;
    [Column('DATA')]
    FData: TDate;

    [Column('COMPRADOR_ID')]
    [ForeignJoinColumn('CompradorId', 'PESSOA', 'ID', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    FCompradorId: Integer;
    [ManyToOne(True, [ckCascadeAll], 'FCompradorId')]
    FComprador: TPessoa;

    [Column('LOTE_ID')]
    [ForeignJoinColumn('LoteId', 'LOTE', 'ID', [fsOnDeleteNoAction, fsOnUpdateNoAction])]
    FLoteId: Integer;
    [ManyToOne(True, [ckCascadeAll], 'FLoteId')]
    FLote: TLote;

    [Column('LANCE_ARREMATE')]
    FLanceArremate: Double;
  public
    constructor Create; virtual;
    destructor Destroy; override;

    property Id: Integer read FId write FId;
    property Data: TDate read FData write FData;

    property CompradorId: Integer read FCompradorId write FCompradorId;
    property Comprador: TPessoa read FComprador write FComprador;

    property LoteId: Integer read FLoteId write FLoteId;
    property Lote: TLote read FLote write FLote;

    property LanceArremate: Double read FLanceArremate write FLanceArremate;
  end;

implementation

uses
  System.SysUtils;

{$REGION 'TVendaLote' }

constructor TVendaLote.Create;
begin
  inherited Create;
  FComprador := TPessoa.Create;
  FLote := TLote.Create;
  FData := Date();
end;

destructor TVendaLote.Destroy;
begin
  FreeAndNil(FComprador);
  FreeAndNil(FLote);
  inherited;
end;

{$ENDREGION}

end.
