unit Syslei.Models.Entities.Pessoa;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('PESSOA')]
  TPessoa = class
  private
    [Column('ID', [cpPrimaryKey])]
    [AutoGenerated]
    FId: Integer;
    [Column('NOME')]
    FNome: String;
    [Column('CPF')]
    FCpf: String;
    [Column('DATA_CADASTRO')]
    FDataCadastro: TDate;
  public
    property Id: Integer read FId write FId;
    property Nome: String read FNome write FNome;
    property Cpf: String read FCpf write FCpf;
    property DataCadastro: TDate read FDataCadastro write FDataCadastro;
  end;

implementation

end.
