unit Syslei.Tests.TestDB.Consts;

interface

const
  LOTE_TABLE_NAME = 'LOTE';
  PESSOA_TABLE_NAME = 'PESSOA';
  PROPRIO_TABLE_NAME = 'PROPRIO';
  VENDA_LOTE_TABLE_NAME = 'VENDA_LOTE';

  LOTE_CREATE_COMMAND =
    'CREATE TABLE IF NOT EXISTS '
  + '[' + LOTE_TABLE_NAME + '] ('
  + '[ID] INTEGER PRIMARY KEY AUTOINCREMENT, '
  + '[DOADOR_ID] INTEGER CONSTRAINT "FK_LOTE_DOADOR" REFERENCES "PESSOA"("ID"), '
  + '[DESCRICAO] VARCHAR(100), '
  + '[NUMERO] VARCHAR(20), '
  + '[LANCE_INICIAL] DECIMAL(15,5), '
  + '[STATUS] INTEGER, '
  + '[TIPO] INTEGER, '
  + '[IDADE] INTEGER, '
  + '[SEXO] INTEGER, '
  + '[DATA_CADASTRO]);';

  PESSOA_CREATE_COMMAND =
    'CREATE TABLE IF NOT EXISTS '
  + '[' + PESSOA_TABLE_NAME + '] ('
  + '[ID] INTEGER PRIMARY KEY AUTOINCREMENT, '
  + '[NOME] VARCHAR(60), '
  + '[CPF_CNPJ] VARCHAR(20), '
  + '[FONE1] VARCHAR(15), '
  + '[DATA_CADASTRO] DATE);';

  PROPRIO_CREATE_COMMAND =
    'CREATE TABLE IF NOT EXISTS '
  + '[' + PROPRIO_TABLE_NAME + '] ('
  + '[ID] INTEGER PRIMARY KEY AUTOINCREMENT, '
  + '[NOME] VARCHAR(60), '
  + '[CPF_CNPJ] VARCHAR(20), '
  + '[FONE1] VARCHAR(15), '
  + '[DATA_CADASTRO] DATE);';

  VENDA_LOTE_CREATE_COMMAND =
    'CREATE TABLE IF NOT EXISTS '
  + '[' + VENDA_LOTE_TABLE_NAME + '] ('
  + '[ID] INTEGER PRIMARY KEY AUTOINCREMENT, '
  + '[COMPRADOR_ID] INTEGER CONSTRAINT "FK_VENDA_LOTE_COMPRADOR" REFERENCES "PESSOA"("ID"), '
  + '[LOTE_ID] INTEGER CONSTRAINT "FK_VENDA_LOTE_LOTE" REFERENCES "LOTE"("ID"), '
  + '[LANCE_ARREMATE] DECIMAL(15,5), '
  + '[DATA] DATE);';

  LOTE_INSERT_COMMAND =
    'INSERT INTO '
  + '[' + LOTE_TABLE_NAME + '] ( '
  + '[DOADOR_ID], [DESCRICAO], [NUMERO], [LANCE_INICIAL], '
  + '[STATUS], [TIPO], [IDADE], [SEXO], [DATA_CADASTRO]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);';

  PESSOA_INSERT_COMMAND =
    'INSERT INTO '
  + '[' + PESSOA_TABLE_NAME + '] ( '
  + '[NOME], [CPF_CNPJ], [FONE1], [DATA_CADASTRO]) VALUES (?, ?, ?, ?);';

  PROPRIO_INSERT_COMMAND =
    'INSERT INTO '
  + '[' + PROPRIO_TABLE_NAME + '] ( '
  + '[NOME], [CPF_CNPJ], [FONE1], [DATA_CADASTRO]) VALUES (?, ?, ?, ?);';

  VENDA_LOTE_INSERT_COMMAND =
    'INSERT INTO '
  + '[' + VENDA_LOTE_TABLE_NAME + '] ('
  + '[COMPRADOR_ID], [LOTE_ID], [LANCE_ARREMATE], [DATA]) VALUES (?, ?, ?, ?);';

  TABLE_DELETE_COMMAND =
    'DELETE FROM [%s];';

implementation

end.
