unit Syslei.Tests.TestDB.Consts;

interface

const
  LOTE_TABLE_NAME = 'LOTE';
  PESSOA_TABLE_NAME = 'PESSOA';

  LOTE_CREATE_COMMAND =
    'CREATE TABLE IF NOT EXISTS '
  + '[' + LOTE_TABLE_NAME + '] ('
  + '[ID] INTEGER PRIMARY KEY AUTOINCREMENT, '
  + '[DOADOR_ID] INTEGER CONSTRAINT "FK_BEM_DOADOR" REFERENCES "PESSOA"("ID"), '
  + '[DESCRICAO] VARCHAR(100), '
  + '[NUMERO] VARCHAR(20), '
  + '[LANCE_INICIAL] DECIMAL(15,5), '
  + '[STATUS] INTEGER, '
  + '[TIPO] INTEGER);';

  PESSOA_CREATE_COMMAND =
    'CREATE TABLE IF NOT EXISTS '
  + '[' + PESSOA_TABLE_NAME + '] ('
  + '[ID] INTEGER PRIMARY KEY AUTOINCREMENT, '
  + '[NOME] VARCHAR(60), '
  + '[CPF] VARCHAR(12), '
  + '[DATA_CADASTRO] DATE);';

  LOTE_INSERT_COMMAND =
    'INSERT INTO '
  + '[' + LOTE_TABLE_NAME + '] ( '
  + '[DOADOR_ID], [DESCRICAO], [NUMERO], [LANCE_INICIAL], [STATUS], [TIPO]) VALUES (?, ?, ?, ?, ?, ?)';

  PESSOA_INSERT_COMMAND =
    'INSERT INTO '
  + '[' + PESSOA_TABLE_NAME + '] ( '
  + '[NOME], [CPF], [DATA_CADASTRO]) VALUES (?, ?, ?)';

  TABLE_DELETE_COMMAND =
    'DELETE FROM [%s]';

implementation

end.
